version: '3.8'

services:
  # 1. The Database
  redis:
    image: redis/redis-stack:latest
    container_name: task_tracker_redis
    ports:
      - "6379:6379"   # Standard Redis
      - "8001:8001"   # RedisInsight UI
    volumes:
      - ./redis-data:/data

  # 2. The Backend
  backend:
    build: ./Backend
    container_name: task_tracker_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - REDIS_URL=redis://redis:6379  # connects to service 'redis'
      - JWT_SECRET=dev_secret
    depends_on:
      - redis
    networks:
      - default

